// Generated by gencpp from file message_gen/arm.msg
// DO NOT EDIT!


#ifndef MESSAGE_GEN_MESSAGE_ARM_H
#define MESSAGE_GEN_MESSAGE_ARM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message_gen
{
template <class ContainerAllocator>
struct arm_
{
  typedef arm_<ContainerAllocator> Type;

  arm_()
    : data()  {
    }
  arm_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::message_gen::arm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_gen::arm_<ContainerAllocator> const> ConstPtr;

}; // struct arm_

typedef ::message_gen::arm_<std::allocator<void> > arm;

typedef boost::shared_ptr< ::message_gen::arm > armPtr;
typedef boost::shared_ptr< ::message_gen::arm const> armConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_gen::arm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_gen::arm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace message_gen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'message_gen': ['/home/soro/catkin_workspace/src/message_gen/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::message_gen::arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_gen::arm_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_gen::arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_gen::arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_gen::arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_gen::arm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_gen::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac9c931aaf6ce145ea0383362e83c70b";
  }

  static const char* value(const ::message_gen::arm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac9c931aaf6ce145ULL;
  static const uint64_t static_value2 = 0xea0383362e83c70bULL;
};

template<class ContainerAllocator>
struct DataType< ::message_gen::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_gen/arm";
  }

  static const char* value(const ::message_gen::arm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_gen::arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] data\n\
";
  }

  static const char* value(const ::message_gen::arm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_gen::arm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_gen::arm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_gen::arm_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_GEN_MESSAGE_ARM_H
