// Generated by gencpp from file message_gen/notification.msg
// DO NOT EDIT!


#ifndef MESSAGE_GEN_MESSAGE_NOTIFICATION_H
#define MESSAGE_GEN_MESSAGE_NOTIFICATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message_gen
{
template <class ContainerAllocator>
struct notification_
{
  typedef notification_<ContainerAllocator> Type;

  notification_()
    : type(0)
    , title()
    , message()  {
    }
  notification_(const ContainerAllocator& _alloc)
    : type(0)
    , title(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _title_type;
  _title_type title;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;




  typedef boost::shared_ptr< ::message_gen::notification_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_gen::notification_<ContainerAllocator> const> ConstPtr;

}; // struct notification_

typedef ::message_gen::notification_<std::allocator<void> > notification;

typedef boost::shared_ptr< ::message_gen::notification > notificationPtr;
typedef boost::shared_ptr< ::message_gen::notification const> notificationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_gen::notification_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_gen::notification_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace message_gen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'message_gen': ['/home/soro/catkin_workspace/src/message_gen/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::message_gen::notification_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_gen::notification_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_gen::notification_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_gen::notification_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_gen::notification_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_gen::notification_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_gen::notification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9106a60b27669e93bbbdcc7e8010c5ec";
  }

  static const char* value(const ::message_gen::notification_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9106a60b27669e93ULL;
  static const uint64_t static_value2 = 0xbbbdcc7e8010c5ecULL;
};

template<class ContainerAllocator>
struct DataType< ::message_gen::notification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_gen/notification";
  }

  static const char* value(const ::message_gen::notification_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_gen::notification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 type\n\
string title\n\
string message\n\
";
  }

  static const char* value(const ::message_gen::notification_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_gen::notification_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.title);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct notification_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_gen::notification_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_gen::notification_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "title: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.title);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_GEN_MESSAGE_NOTIFICATION_H
