// Generated by gencpp from file message_gen/ping.msg
// DO NOT EDIT!


#ifndef MESSAGE_GEN_MESSAGE_PING_H
#define MESSAGE_GEN_MESSAGE_PING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Soro
{
namespace Messages
{

template <class ContainerAllocator>
struct ping_
{
  typedef ping_<ContainerAllocator> Type;

  ping_()
    : sender()
    , id(0)  {
    }
  ping_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef uint64_t _id_type;
  _id_type id;




  typedef boost::shared_ptr< ::Soro::Messages::ping_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Soro::Messages::ping_<ContainerAllocator> const> ConstPtr;

}; // struct ping_

typedef ::Soro::Messages::ping_<std::allocator<void> > ping;

typedef boost::shared_ptr< ::Soro::Messages::ping > pingPtr;
typedef boost::shared_ptr< ::Soro::Messages::ping const> pingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Soro::Messages::ping_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Soro::Messages::ping_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Messages
} // namespace Soro

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'message_gen': ['/home/soro/catkin_workspace/src/message_gen/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Soro::Messages::ping_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Soro::Messages::ping_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Soro::Messages::ping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Soro::Messages::ping_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Soro::Messages::ping_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Soro::Messages::ping_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Soro::Messages::ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1319c22bde918e62ad857dc22825b457";
  }

  static const char* value(const ::Soro::Messages::ping_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1319c22bde918e62ULL;
  static const uint64_t static_value2 = 0xad857dc22825b457ULL;
};

template<class ContainerAllocator>
struct DataType< ::Soro::Messages::ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_gen/ping";
  }

  static const char* value(const ::Soro::Messages::ping_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Soro::Messages::ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n\
uint64 id\n\
";
  }

  static const char* value(const ::Soro::Messages::ping_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Soro::Messages::ping_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ping_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Soro::Messages::ping_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Soro::Messages::ping_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_GEN_MESSAGE_PING_H
