// Generated by gencpp from file ros_generated/data_rate.msg
// DO NOT EDIT!


#ifndef ROS_GENERATED_MESSAGE_DATA_RATE_H
#define ROS_GENERATED_MESSAGE_DATA_RATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_generated
{
template <class ContainerAllocator>
struct data_rate_
{
  typedef data_rate_<ContainerAllocator> Type;

  data_rate_()
    : dataRateUp(0)
    , dataRateDown(0)  {
    }
  data_rate_(const ContainerAllocator& _alloc)
    : dataRateUp(0)
    , dataRateDown(0)  {
  (void)_alloc;
    }



   typedef uint64_t _dataRateUp_type;
  _dataRateUp_type dataRateUp;

   typedef uint64_t _dataRateDown_type;
  _dataRateDown_type dataRateDown;




  typedef boost::shared_ptr< ::ros_generated::data_rate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_generated::data_rate_<ContainerAllocator> const> ConstPtr;

}; // struct data_rate_

typedef ::ros_generated::data_rate_<std::allocator<void> > data_rate;

typedef boost::shared_ptr< ::ros_generated::data_rate > data_ratePtr;
typedef boost::shared_ptr< ::ros_generated::data_rate const> data_rateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_generated::data_rate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_generated::data_rate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_generated

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_generated': ['/home/soro/catkin_workspace/src/ros_generated/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_generated::data_rate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_generated::data_rate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_generated::data_rate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_generated::data_rate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_generated::data_rate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_generated::data_rate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_generated::data_rate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8e8e5eaab2e1f98c66dca72fa8cba64";
  }

  static const char* value(const ::ros_generated::data_rate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8e8e5eaab2e1f98ULL;
  static const uint64_t static_value2 = 0xc66dca72fa8cba64ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_generated::data_rate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_generated/data_rate";
  }

  static const char* value(const ::ros_generated::data_rate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_generated::data_rate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 dataRateUp\n\
uint64 dataRateDown\n\
";
  }

  static const char* value(const ::ros_generated::data_rate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_generated::data_rate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dataRateUp);
      stream.next(m.dataRateDown);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct data_rate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_generated::data_rate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_generated::data_rate_<ContainerAllocator>& v)
  {
    s << indent << "dataRateUp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.dataRateUp);
    s << indent << "dataRateDown: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.dataRateDown);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GENERATED_MESSAGE_DATA_RATE_H
