// Generated by gencpp from file ros_generated/drive.msg
// DO NOT EDIT!


#ifndef ROS_GENERATED_MESSAGE_DRIVE_H
#define ROS_GENERATED_MESSAGE_DRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_generated
{
template <class ContainerAllocator>
struct drive_
{
  typedef drive_<ContainerAllocator> Type;

  drive_()
    : wheelFL(0)
    , wheelFR(0)
    , wheelML(0)
    , wheelMR(0)
    , wheelBL(0)
    , wheelBR(0)  {
    }
  drive_(const ContainerAllocator& _alloc)
    : wheelFL(0)
    , wheelFR(0)
    , wheelML(0)
    , wheelMR(0)
    , wheelBL(0)
    , wheelBR(0)  {
  (void)_alloc;
    }



   typedef int8_t _wheelFL_type;
  _wheelFL_type wheelFL;

   typedef int8_t _wheelFR_type;
  _wheelFR_type wheelFR;

   typedef int8_t _wheelML_type;
  _wheelML_type wheelML;

   typedef int8_t _wheelMR_type;
  _wheelMR_type wheelMR;

   typedef int8_t _wheelBL_type;
  _wheelBL_type wheelBL;

   typedef int8_t _wheelBR_type;
  _wheelBR_type wheelBR;




  typedef boost::shared_ptr< ::ros_generated::drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_generated::drive_<ContainerAllocator> const> ConstPtr;

}; // struct drive_

typedef ::ros_generated::drive_<std::allocator<void> > drive;

typedef boost::shared_ptr< ::ros_generated::drive > drivePtr;
typedef boost::shared_ptr< ::ros_generated::drive const> driveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_generated::drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_generated::drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_generated

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'ros_generated': ['/home/jj/Projects/catkin_workspace/src/ros_generated/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::ros_generated::drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_generated::drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_generated::drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_generated::drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_generated::drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_generated::drive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_generated::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9cd6dc5f687cf0d3cbd747212dba324a";
  }

  static const char* value(const ::ros_generated::drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9cd6dc5f687cf0d3ULL;
  static const uint64_t static_value2 = 0xcbd747212dba324aULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_generated::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_generated/drive";
  }

  static const char* value(const ::ros_generated::drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_generated::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 wheelFL\n\
int8 wheelFR\n\
int8 wheelML\n\
int8 wheelMR\n\
int8 wheelBL\n\
int8 wheelBR\n\
";
  }

  static const char* value(const ::ros_generated::drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_generated::drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wheelFL);
      stream.next(m.wheelFR);
      stream.next(m.wheelML);
      stream.next(m.wheelMR);
      stream.next(m.wheelBL);
      stream.next(m.wheelBR);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_generated::drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_generated::drive_<ContainerAllocator>& v)
  {
    s << indent << "wheelFL: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wheelFL);
    s << indent << "wheelFR: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wheelFR);
    s << indent << "wheelML: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wheelML);
    s << indent << "wheelMR: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wheelMR);
    s << indent << "wheelBL: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wheelBL);
    s << indent << "wheelBR: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wheelBR);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GENERATED_MESSAGE_DRIVE_H
